version: '3'

networks:
  containers:
    ipam:
      config:
        - subnet: 172.31.0.0/24

services:
  app:
    image: 'jc21/nginx-proxy-manager:2.8.1'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "172.31.0.7"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "S3cr3t0"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    networks:
      containers:
        ipv4_address: 172.31.0.6
  db:
    image: 'jc21/mariadb-aria:10.4.15'
    environment:
      MYSQL_ROOT_PASSWORD: 'Sup3rS3cr3t0'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'S3cr3t0'
    volumes:
      - ./mariadb/data/mysql:/var/lib/mysql
    networks:
      containers:
        ipv4_address: 172.31.0.7