version: '3.3'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:v5.7
    dns:
      - "127.0.0.1"
      - "1.1.1.1"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
      WEBPASSWORD: S3cr3t0
    volumes:
      - '/opt/docker/pihole/pihole/etc/pihole/:/etc/pihole/'
      - '/opt/docker/pihole/etc/dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped