# MariaDB 10.6
version: '3.1'
services:
  db:
    image: mariadb:10.6-focal
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - MARIADB_ROOT_PASSWORD: S3cr3t0
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - TZ=America/Argentina/Buenos_Aires